### PR TITLE
WP-API: Utilize apiNamespace not version to determine base path.

### PR DESCRIPTION
**Pull request by timmyc**
Changing up the version based approach, sorry for that, details here https://github.com/Automattic/wpcom.js/pull/151

/cc @retrofox

### CODE REVIEW

**Comment by retrofox** [comment]
:+1: Let's be sure before to make a new release.

**Comment by timmyc** [comment]
Agreed.  We spent quite a bit of time during our team hangout last week debating the api path.  I'm fairly certain `apiVersion` is going to be the route to take and will be future proof ( famous last words right?? )

**Comment by retrofox** [comment]
> famous last words right?? 

Indeed :-D

**Comment by timmyc** [comment]
Okay to merge this one - and do you want me to do some PRs for builds or not sure the flow on that here and in wpcom.js

**Comment by retrofox** [comment]
> do you want me to do some PRs for builds or not sure the flow on that here and in wpcom.js

If you have the chance it would be great ( and especially useful :-) ).

**Pull request merged**
