### PR TITLE
Prevent sending body if formData is set

### PR DESCRIPTION
**Pull request by sirbrillig**
As [explained in this issue](https://github.com/visionmedia/superagent/pull/1154), superagent cannot use a mix of `send()` and `field()`. This makes sense since `field()` is a shortcut which constructs a multipart `FormData` message (including setting all appropriate headers), and `send()` is used for manually sending data. If `send()` is used, headers like `content-type` would need to be sent manually also, but that would be challenging because that header [requires a boundary](https://github.com/visionmedia/superagent/issues/1152#issuecomment-271663641).

Of course, this shouldn't be an issue because why would someone set a `body` property in a request if `formData` is also set? 

Well, as [I discovered](https://github.com/Automattic/wp-calypso/pull/15636#issuecomment-312696852), the [wpcom.js](https://github.com/Automattic/wpcom.js) module (which is used in place of wpcom-xhr-request when not using oAuth in [calypso](https://github.com/Automattic/wp-calypso), and so shares the same API) automatically [will delete a `formData` request if there is no `body` (and no callback) set](https://github.com/Automattic/wpcom.js/blob/ab065dfc1e515aba6e36cb9b6b438366dff9bc3c/lib/util/request.js#L43). Moreover, if `body` is not set, the `apiNamespace` field will just be copied into a new `body` object instead (not quite sure yet where that happens, but it does). 

Therefore, it is necessary to set an empty `body` to make a request from wp-calypso that sets `formData`, but that empty body should not break the form encoding done by superagent. 

This change will simply assume that `formData` should take precedence over any `body` data and ignore `body` if both are set.

### CODE REVIEW

**Comment by sirbrillig** [comment]
I've added a unit test to try to prove this, but unfortunately it passes even without the fix. 😠  Still trying to get it to fail correctly.

I've been able to prove that this solves the issue by doing the following steps:

1. clone the wp-desktop repo
2. in the calypso submodule, checkout `93a64c6c1028b2ba0e196b65872a21db8128ed5c`
3. `make run` the desktop app
4. Visit the /me route by clicking the avatar icon in the masterbar.
5. Click the Gravatar icon in the page center and upload a new image.
6. see the Gravatar upload fails with a json syntax error
7. Inside the wp-desktop repo clone, edit `wp-desktop/calypso/node_modules/wpcom-xhr-request/build/index.js` and add the patch above.
8. Run `make build` in wp-desktop.
9. Repeat steps 3-5 and verify that the upload succeeds.

**Comment by sirbrillig** [comment]
Ah, it passes because https://github.com/visionmedia/superagent/pull/1154 has not been merged yet so superagent will silently allow the process to work but will actually fail. I think that the version of superagent used here doesn't even have [this version of the check](https://github.com/visionmedia/superagent/pull/1153). 

You can get the unit test to fail by applying [this patch](https://gist.github.com/sirbrillig/a4dfe8c60d3af606fa059e776fb575a5) and then running the tests.

**Comment by v18** [comment]
I was able to repro the fix on Desktop 👍 I wasn't yet able to run the unit tests, but it's getting late here so I will continue looking tomorrow.

**Comment by v18** [comment]
Unit tests are passing. `Content-Type` is getting set to `multipart/form-data` 👍 . From my previous experience with superagent (and having just looked it up again), it sets the `Content-Type` header based on using `attach` or `field` (and defaulting to `application/json`).

With your fix, `attach` and `field` do not happen together with `send`, which looks good to me.

**Comment by youknowriad** [comment]
It's been a long time I haven't run Calypso or WP-Desktop. So, for some reason I'm not able to test the fix (all my debugs and console.logs in the patched file are not being shown). Not sure what am I missing.

But anyway, the fix seems logical to me.

**Comment by sirbrillig** [comment]
Thanks, @youknowriad! It's possible you missed the `make build` step above (if testing in wp-desktop), but there could be something else going on. In any case, the change is fairly simple as you said.

Going to merge tomorrow if there are no objections.

**Pull request merged**
